language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
    - CONFIGURE_ARGS='-Uusethreads'
    - CONFIGURE_ARGS='-Dusethreads'
    - CONFIGURE_ARGS='-Duselongdouble'
    - CONFIGURE_ARGS='-Duse64bitall'
    - CONFIGURE_ARGS='-Dusethreads -Duselongdouble'
    - CONFIGURE_ARGS='-Dusethreads -Duse64bitall'
    - CONFIGURE_ARGS='-Dusethreads -Duse64bitall -Duselongdouble'

script:
  - ./Configure -des -Dusedevel -Uversiononly -Dcc=$CC $CONFIGURE_ARGS -Dprefix=$HOME/perl-blead -DDEBUGGING && TEST_JOBS=4 make -j4 test_harness && make install && $HOME/perl-blead/bin/perlivp

addons:
    apt:
        packages:
            - file
            - cpio
            - libdb-dev
            - libgdbm-dev
            - zlib1g-dev
            - libbz2-dev
